### ISSUE TITLE
""Bugs"" noticed when playing 

### ISSUE THREAD

**Issue by AzhamProdLive** [kkrosie123/eliana-circe-ypd#38]
As playtester imma drop here all the small bugs i found in there (they are maybe left there on purpose but ye)
- When you press the Skip button (CTRL on Azerty keyboard), all the Eliana animations are skipped when idle 
- Changing Pronoun dialogue is rolling, i think it should be better if she only ask if we changed our pronouns only once, js 
- Dialogue is not listed in the "Dialogue History"
- When you "sacrifice" holy water to Eliana, i think the game should close, like, she's angy and she decided to close the game to calm down idk, just givin' ideas

imma use this Issue thing to drop all the things i noticed while testing

**Comment by kkrosie123** [comment]
- noted, i need to disable the skip button
- Will work on that
- I still am unsure what causes this but i noticed this too. Will look into it
- Eliana is not aware she is in a game, we don't want to have any meta mechanics


Thank you for reporting these!
